### ISSUE TITLE
Plugin loads resources on non-cp requests

### ISSUE THREAD

**Issue by alexbech** [benjamminf/craft-quick-field#11]
The plugin loads js and css resources when logged in as admin, even for non-cp requests.
This leads to errors because I'm not loading jQuery on my site.

**Comment by benjamminf** [comment]
Really? This is interesting, as [this line](https://github.com/benjamminf/craft-quick-field/blob/master/quickfield/QuickFieldPlugin.php#L57) should ensure it won't do that. Might be a stupid question but are you running the latest version of Quick Field (0.3.3)?

**Comment by alexbech** [comment]
I'm so sorry, you are of course right! I downloaded the latest plugin, but somehow must have managed to copy an old version. My bad!
