### ISSUE TITLE
No Error (hangs) on new field when no field groups exist

### ISSUE THREAD

**Issue by billythekid** [benjamminf/craft-quick-field#12]
I appreciate this is a very small thing that nobody's likely to ever encounter but here you go anyway!

There's no check on the existence of field groups before the New Field button is shown on field layouts. Clicking this button gives a hanging modal.

Replicate:

- Vanilla craft with quick fields installed
- Remove all field groups
- Edit a section
- Click the New Field button.

**Comment by ttempleton** [comment]
Just added a fix for this for the upcoming Quick Field 1.0.0 release.
