### ISSUE TITLE
Stupidly long field groups overlay "new" buttons

### ISSUE THREAD

**Issue by billythekid** [benjamminf/craft-quick-field#14]
Heya, 

Not sure how this is best fixed hopefully just a css tweak (taking the clear: both off of .fieldlayoutform.quick-field .newfieldbtn-container "fixes" this but causes other weirdness at different screen sizes)

If you have insanely long field groups they can overlay the quickfield buttons:

![screen shot 2017-02-28 at 15 44 18](https://cloud.githubusercontent.com/assets/330170/23412232/d9b73fae-fdcc-11e6-9e1d-c37aaa127dae.png)

**Comment by ttempleton** [comment]
Going to close this issue now, since the Craft 2 version of the plugin is no longer supported, and this issue doesn't apply to the upcoming Craft 3.7/4.x versions due to the field layout designer overhaul in Craft 3.5.
