### ISSUE TITLE
Unhelpful error messages.

### ISSUE THREAD

**Issue by billythekid** [benjamminf/craft-quick-field#15]
If a field fails to save, two "An error has occurred" messages are shown but there's nothing letting you know what happened. For example save a matrix field with a field in it using a reserved word, such as 'name'. It won't save obviously but the error doesn't let you know all you need to do is change the handle from a reserved word to fix it.

**Comment by ttempleton** [comment]
It turned out that we were never getting back the validation error messages because the invalid field handle was causing a 500 error in the Craft 2 version. That should now be working as expected in the Craft 3/4 versions.
