### ISSUE TITLE
This coming to C3?

### ISSUE THREAD

**Issue by nexflo** [benjamminf/craft-quick-field#16]
Plug rocks. Should really be native ;)

**Comment by mikethehud** [comment]
According to [the neo readme](https://github.com/benjamminf/craft-neo/blob/dev-3-port/README.md) this will be coming to Craft 3, but seems to be a while until it's happening.

**Comment by JayBox325** [comment]
Still no news or updates on this plugin on this repo or on the Neo repo.

**Comment by j-greig** [comment]
Missing you X

**Comment by bstein-clever** [comment]
Will @spicywebau be taking this one over, too? Or just Neo?

**Comment by hassanLDA** [comment]
Is there any updates on this coming to Craft 3?

**Comment by ttempleton** [comment]
> Will @spicywebau be taking this one over, too?

The (slightly late 😅) answer to this is **yes**. The Craft 3 version should be out by the end of the month, and the Craft 4 version in July.

**Comment by ttempleton** [comment]
We've just tagged the 1.0.0 release and submitted the plugin for approval for the plugin store. I'll close this issue now, but will comment here again when the Craft 4 version is released.

**Comment by ttempleton** [comment]
Just released Quick Field 2.0.0, for Craft 4.1.0 or later.
