### ISSUE TITLE
Buttons not showing in Craft 4.2.0.2

### ISSUE THREAD

**Issue by martinherweg** [benjamminf/craft-quick-field#17]
Hey,

I have installed the plugin but in the Field Layout Designer the buttons are not showing.

Craft Version is 4.2.0.2 and Plugin version 2.0.1

Is there anything I missed ?

![image](https://user-images.githubusercontent.com/381383/181771989-cde91f33-2486-4c1d-a33b-8ab5da6a07cb.png)
![image](https://user-images.githubusercontent.com/381383/181772057-466b4878-d48f-417c-97c7-33918f05730b.png)

Thanks :)

**Comment by ttempleton** [comment]
Are there any errors in the browser console?

If not, is this happening on the field layout designer for an entry type, category group, or other element type (or any field layout designer regardless of element type)?

**Comment by martinherweg** [comment]
@ttempleton No console errors, same for every field layout designer.

**Comment by ttempleton** [comment]
Does it happen in any browser you try it with?

If it does, then if possible, could you please send your database backup and composer.json/lock to plugins@spicyweb.com.au and we'll have a look.

**Comment by martinherweg** [comment]
@ttempleton Unfortunately this is isn't possible but I've found the issue, in the `_includeResources` function the condition solves to `false` not sure which of the conditions though.

Edit: I've logged the conditions and this is the result
![image](https://user-images.githubusercontent.com/381383/181788099-88ba0f83-fd2b-44cb-8a72-d804b46187f9.png)

**Comment by ttempleton** [comment]
Thanks for pointing that out, seems like https://github.com/craftcms/cms/issues/11033 is getting involved here.

I've just released Quick Field 2.0.2 which follows the advice from https://github.com/craftcms/cms/issues/11033#issuecomment-1111754160 which should resolve this. Please do let me know if that hasn't resolved it, though, and I'll reopen the issue.
