### ISSUE TITLE
Save as new field does not work for Matrix fields in Craft 4.4

### ISSUE THREAD

**Issue by zizther** [benjamminf/craft-quick-field#19]
### Bug Description

Since upgrading to Craft 4.4 I am not able to use the `Save as new field` button within the Quick Field modal for matrix fields

Error message
`Cannot assign string to property craft\models\MatrixBlockType::$fieldId of type ?int in /var/www/html/vendor/craftcms/cms/src/fields/Matrix.php:297`

### Steps to reproduce

1. Create a new matrix field using Quick Fields
2. Edit the field in Quick Fields modal (update the name and handle)
3. Try to `Save as new field`

I am also trying to save the new field from within a Neo field in the CP.

### Quick Field version

2.0.3

### Craft CMS version

4.4.7.1

**Comment by ttempleton** [comment]
Thanks for reporting this - fixed now in 2.0.4.
