### ISSUE TITLE
"Use this field’s values as search keywords" checkbox not saved

### ISSUE THREAD

**Issue by nstcactus** [benjamminf/craft-quick-field#20]
### Bug Description

When creating or editing a field using quick field, the Craft "Use this field’s values as search keywords" checkbox value isn't saved. 

### Steps to reproduce

1. Go to a section settings
2. Edit one of its entry types
3. Create a field using the quick field modal
5. Select the "Use this field’s values as search keywords"
6. Save the field
7. Edit the field using Craft native UI to see the "Use this field’s values as search keywords" isn't checked

### Expected behaviour

The "Use this field’s values as search keywords" value should be saved

### Quick Field version

2.0.5

### Craft CMS version

4.5.6.1

**Comment by ttempleton** [comment]
Thanks for reporting that - fixed now in 2.0.6.
