### ISSUE TITLE
Edit current fields/groups

### ISSUE THREAD

**Issue by benjamminf** [benjamminf/craft-quick-field#3]
Add ability to edit the current fields and field groups. I'm imagining "cog" buttons next to unused fields and groups that drop down a menu with the option to edit or delete. So similar functionality to the solid bordered tabs and fields.

**Comment by nexflo** [comment]
Yup, digg that one as well. Maybe just double click as you've implemented modals anyhow.

**Comment by benjamminf** [comment]
Editing and deleting fields is now supported in version 0.3.0

Editing and deleting groups will be supported in the next (edit: major) release.

**Comment by sjelfull** [comment]
@benjamminf I don't see the ability to edit fields that belong to the layout. Is this added, or by current do you mean fields that exist in the system?

On 0.3.2.

![image](https://cloud.githubusercontent.com/assets/10508/14501945/24ca98cc-01a9-11e6-95db-e7a72df7673c.png)

**Comment by benjamminf** [comment]
@sjelfull Yeah that's not supported (yet). This plugin hasn't had much love lately, but once uni's semester is over I plan on implementing this long overdue feature and a few others.

**Comment by ttempleton** [comment]
Editing and deleting field groups now supported in version 1.0.0 (for Craft 3.7).

Editing and deleting fields on the field layout will be supported in version 2.0.0 (for Craft 4).
